"""empty message

Revision ID: 89db78056865
Revises: 3a686bd0fc55
Create Date: 2021-06-25 10:58:51.087654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89db78056865'
down_revision = '3a686bd0fc55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
